# dev stage image
FROM golang:1.16 AS dev-stage
ENV GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /app
COPY . .
RUN go mod download
# Air hotreload see .air.toml for configuration
RUN apt update && apt upgrade -y && \
    apt install -y git \
    make openssh-client
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air
EXPOSE 8000
CMD air